### ISSUE TITLE
Proportional ATTs for Poisson Regressions

### ISSUE THREAD

**Issue by frederickluser** [grantmcdermott/etwfe#47]
Dear @grantmcdermott , Dear @vincentarelbundock - a question regarding the marginal effects in `etwfe.`

I want to use `etwfe` with a Poisson specification, reporting the overall ATT as a percentage change (i.e., "Employment decreased by x% due to the treatment"). Here is a super simple example with only one coefficient:

```r 
# Load the data
data("mpdta")
mpdta$emp <- exp(mpdta$lemp)

# Regression
(mod = etwfe(
        fml  = emp ~ 0,
        tvar = year,     
        gvar = first.treat, 
        family = "quasipoisson",
        data = mpdta %>% dplyr::filter(year %in% c(2004, 2005), first.treat %in% c(2004, 2005, 2006)),     
        vcov = ~countyreal
    ))

# Output
GLM estimation, family = quasipoisson, Dep. Var.: emp
Observations: 120 
Fixed-effects: first.treat: 2,  year: 2
Standard-errors: Clustered (countyreal) 
                                      Estimate Std. Error  t value Pr(>|t|)    
.Dtreat:first.treat::2004:year::2005 -0.050079    0.02777 -1.80335  0.07644 .  

# Aggregation / Marginal Effect
mod2 <- emfx(mod)
  Term                 Contrast .Dtreat Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %
 .Dtreat mean(TRUE) - mean(FALSE)    TRUE    -36.9         20 -1.85   0.0644 4.0 -76.1   2.21
```

I want to get the marginal effects as percentage changes. I was hoping I could simply relate the marginal ATT reported by `emfx` to the mean of the control group pre-treatment. In this example, I think it should be:
```r 
dat <- data.table::as.data.table(eval(mod$call$data, mod$call_env))
mod2$estimate / ( dat%>% dplyr::filter(year == 2004, first.treat == 2006) %>% pull(emp) %>% mean() )
```

But then, could in general the following be correct?
```r 
dat <- data.table::as.data.table(eval(mod$call$data, mod$call_env))
mod2$estimate / (dat %>% dplyr::filter(year < first.treat) %>% pull(emp) %>% mean() )
```

Does that make any sense? Any feedback is highly appreciated.

**Comment by spearmint4** [comment]
I apologize if this is redundant to the request above. I bring a comparison with 'jwdid' in Stata as I believe that was a benchmark. 

R code with 'etwfe'
```
data("mpdta", package = "did")
mpdta$emp = exp(mpdta$lemp)

mod = etwfe(
  emp ~ 1, tvar = year, gvar = first.treat, data = mpdta, vcov = ~countyreal,
  family = "poisson"
) 
emfx(mod, "event")
```
Is equivalent to Stata code below with 'jwdid'

```
jwdid emp, ivar(countyreal) tvar(year) gvar(first_treat) method(poisson)
estat event
```
Which gives the output 
```
event Estimate Std. Error      z Pr(>|z|)    S  2.5 % 97.5 %
     0  -25.572       16.5 -1.548  0.12161  3.0  -57.9    6.8
     1    0.874       51.4  0.017  0.98645  0.0  -99.9  101.7
     2  -76.747       28.5 -2.690  0.00715  7.1 -132.7  -20.8
     3 -102.358       28.4 -3.607  < 0.001 11.7 -158.0  -46.7
```
'jwdid' in Stata has the option to use `estat event, predict(xb)`, which results in the output below. Is there an efficient way to do something similar with 'etwfe'?

```
------------------------------------------------------------------------------
             |            Delta-method
             | Coefficient  std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
   __event__ |
          0  |   -.030895   .0123785    -2.50   0.013    -.0551564   -.0066335
          1  |  -.0010715   .0286099    -0.04   0.970    -.0571459    .0550028
          2  |   -.051965   .0197745    -2.63   0.009    -.0907222   -.0132077
          3  |  -.0672208   .0192207    -3.50   0.000    -.1048926    -.029549
------------------------------------------------------------------------------

```

**Comment by grantmcdermott** [comment]
Hi @spearmint4, thanks for the question.

(Also @frederickluser, so sorry for not responding to your original question! I completely missed it at the time, but hopefully my answer below is relevant for you too.)

First, let me provide some code that gives the same answer as your Stata output:

```r
marginaleffects::slopes(
  mod, 
  newdata   = transform(subset(fixest:::fetch_data(mod), .Dtreat), event = year - first.treat),
  variables = ".Dtreat", 
  by        = "event",
  type      = "link"
)
#> event Estimate Std. Error       z Pr(>|z|)    S   2.5 %   97.5 %
#>     0 -0.03089     0.0124 -2.4889  0.01281  6.3 -0.0552 -0.00657
#>     1 -0.00107     0.0287 -0.0373  0.97021  0.0 -0.0573  0.05516
#>     2 -0.05196     0.0198 -2.6206  0.00878  6.8 -0.0908 -0.01310
#>     3 -0.06722     0.0193 -3.4876  < 0.001 11.0 -0.1050 -0.02944
```

The key argument here is `type = "link"`, which has the same linearizing effect at Stata's `margins, predicti(xb)`. Let me explain a bit more below...

### Explanation

As you may know, `emfx()` is light wrapper around [marginaleffects::slopes()](https://marginaleffects.com/r/man/slopes.html) that does some minor data subsetting and grouping. (Details [here](https://grantmcdermott.com/etwfe/articles/etwfe.html#manual-implementation).) The above code is basically equivalent to what we do internally for `emfx()`... except that I've specified the `type = "link"` argument, as motivated above.

Now, `emfx(...)` allows you to pass additional arguments to `marginalaffects::slopes()`. So why can't we just pass `type = "link"` argument as part of `emfx(..., type = "link")`? Well, unfortunately that would clash with the top level `type = "event"` argument that specifies the type of aggregation. In hindsight, I rather wish I had chosen a different argument and avoided this argument class, but that ship has sailed. 

I'll think of appropriate way / argument to pass things down automatically from `emfx()`. (Maybe `scale = "link"`). But in the meantime you can at least use the manual approach I show above.

**Comment by grantmcdermott** [comment]
@spearmint4 I've just added an `emfx(..., predict)` argument, which you can assign the "link" value to. This obtains the linear prediction and generates the result you are looking for.

``` r
data("mpdta", package = "did")
mpdta$emp = exp(mpdta$lemp)

library(etwfe)

etwfe(
  emp ~ 1, tvar = year, gvar = first.treat, data = mpdta, vcov = ~countyreal,
  family = "poisson"
) |>
  emfx(type = "event", predict = "link")
#> The variables '.Dtreat:first.treat::2006:year::2004', '.Dtreat:first.treat::2006:year::2005', '.Dtreat:first.treat::2007:year::2004', '.Dtreat:first.treat::2007:year::2005' and '.Dtreat:first.treat::2007:year::2006' have been removed because of collinearity (see $collin.var).
#> 
#>  event Estimate Std. Error       z Pr(>|z|)    S   2.5 %   97.5 %
#>      0 -0.03089     0.0124 -2.4889  0.01281  6.3 -0.0552 -0.00657
#>      1 -0.00107     0.0287 -0.0373  0.97021  0.0 -0.0573  0.05516
#>      2 -0.05196     0.0198 -2.6206  0.00878  6.8 -0.0908 -0.01310
#>      3 -0.06722     0.0193 -3.4876  < 0.001 11.0 -0.1050 -0.02944
#> 
#> Term: .Dtreat
#> Type:  link 
#> Comparison: mean(TRUE) - mean(FALSE)
#> Columns: term, contrast, event, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted
```

See the README for instructions on how to install the dev version from R-universe.

**Comment by grantmcdermott** [comment]
Closing this issue now. Please let me know if you think it should be re-opened.
